import { v4 as uuid } from 'uuid';
/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [

  {
    _id: uuid(),
    title: "THE BEST 'SUHAGRAAT' VLOG EVER | LAKSHAY CHAUDHARY",
    thumbnail: "https://i.ytimg.com/vi/hPJ762sAptY/maxresdefault.jpg",
    iframe: `width="100%" height="315" src="https://www.youtube.com/embed/hPJ762sAptY" title="YouTube video player" frameborder="0" allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture; " allowFullScreen="allowFullScreen"`,
    category: "vlogs",
    likes: 666,
    liked: null,
    disliked: null,
    notes: [],
    description: "The Best Honeymoon Aka Shadi Ki Pehli Raat Vlog Ever XD. Witness this journey with us.",
    channelName: "Lakshay Choudhary",
  },

  {
    _id: uuid(),
    title: "The Most Important Movie I've Ever Made",
    thumbnail: "https://i.ytimg.com/vi/UVA8pPxOPk4/maxresdefault.jpg",
    iframe: `width="100%" src="https://www.youtube.com/embed/UVA8pPxOPk4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen="allowFullScreen">`,
    category: "vlogs",
    likes: 666,
    liked: null,
    disliked: null,
    notes: [],
    description: "my 30-day online filmmaking & storytelling class just launched! Enrollment is open now until December 27.  the class is a hands-on, 30-day learning experience, designed to teach you everything I know about filmmaking and storytelling, i'm going to share with you my entire creative process from start to finish. You're going to follow along with me as I create 2 brand new movies from scratch... from how I come up the ideas, all the way through exporting the final videos.",
    channelName: "CaseyNeistat",
  },

  {
    _id: uuid(),
    title: "HIDDEN VIDEO CAMERA in my Custom Glasses",
    thumbnail: "https://i.ytimg.com/vi/PF3iysOyelg/maxresdefault.jpg",
    iframe: `width="100" src="https://www.youtube.com/embed/PF3iysOyelg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen="allowFullScreen">`,
    category: "vlogs",
    likes: 666,
    liked: null,
    disliked: null,
    notes: [],
    description: "check out my filmmaking class!!!",
    channelName: "CaseyNeistat",
  },

  {
    _id: uuid(),
    title: "How To Get Into Harvard (from India)",
    thumbnail: "https://i.ytimg.com/vi/CuYSxik-kUs/maxresdefault.jpg",
    iframe: `width="100" src="https://www.youtube.com/embed/CuYSxik-kUs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen="allowFullScreen">`,
    category: "education",
    likes: 666,
    liked: null,
    disliked: null,
    notes: [],
    description: "I went to high school in Mumbai, and was the only one from India accepted to Harvard early admission my year! Here are a few tips and tricks for preparing your application and applying to Harvard internationally. Feel free to leave any questions in the comments below! 💜💗",
    channelName: "Avanti Nagral",
  },

  {
    _id: uuid(),
    title: "Sadhguru On What's Wrong With Today's Education System | Mystics Of India",
    thumbnail: "https://i.ytimg.com/vi/SSTfPHBCVgo/maxresdefault.jpg",
    iframe: `width="100" src="https://www.youtube.com/embed/SSTfPHBCVgo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen="allowFullScreen">`,
    category: "education",
    likes: 666,
    liked: null,
    disliked: null,
    notes: [],
    description: `* Copyright Disclaimer Under Section 107 of the Copyright Act 1976, allowance is made for "fair use" for purposes such as criticism, commenting, news reporting, teaching, scholarship, and research. Fair use is a use permitted by copyright statute that might otherwise be infringing. Non-profit, educational or personal use tips the balance in favor of fair use.`,
    channelName: "Mystics OF India",
  },

  {
    _id: uuid(),
    title: "Indian Education System Ka DARK Truth - FAILURE? - Ranveer Allahbadia ",
    thumbnail: "https://i.ytimg.com/vi/7uLdaQPekmI/maxresdefault.jpg",
    iframe: `width="100" src="https://www.youtube.com/embed/7uLdaQPekmI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen="allowFullScreen">`,
    category: "education",
    likes: 666,
    liked: null,
    disliked: null,
    notes: [],
    description: `TRS Clips हिंदी आपके Favourite The Ranveer Show हिंदी Podcast के Short Clips का एक बेहतरीन Collection है। आप सबके Love & Support से Ranveer Allahbadia द्वारा The Ranveer Show हिंदी पूरे India के सभी Audio Platforms पर Biggest हिंदी Podcast बन चुका है। BeerBiceps की Team आशा करती है कि हमारे द्वारा बनाए इन ज्ञान से भरे Videos को आप ज़रूर Enjoy करेंगे।`,
    channelName: "TRS Clips हिंदी",
  },

  {
    _id: uuid(),
    title: "World's Craziest Adventure Park! (Inside a Jungle)",
    thumbnail: "https://i.ytimg.com/vi/cSLQ2fHR5Gg/maxresdefault.jpg",
    iframe: `width="100" src="https://www.youtube.com/embed/cSLQ2fHR5Gg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen="allowFullScreen">`,
    category: "adventure",
    likes: 666,
    liked: null,
    disliked: null,
    notes: [],
    description: "We visit the central America region for the first time. In the country of Mexico, we visit Cancun. In her lies the craziest adventure park in the whole world! A mix of jungle rivers, ziplines and underground caves",
    channelName: "Dhruv Rathee Vlogs",
  },

  {
    _id: uuid(),
    title: "Exploring World's Largest Abandoned Theme Park - Wonderland Eurasia",
    thumbnail: "https://i.ytimg.com/vi/wpst0Dbbk7U/maxresdefault.jpg",
    iframe: `width="100" src="https://www.youtube.com/embed/wpst0Dbbk7U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen="allowFullScreen">`,
    category: "adventure",
    likes: 666,
    liked: null,
    disliked: null,
    notes: [],
    description: `In today's episode, we're exploring Wonderland Eurasia, also known as Ankapark.
    Opened in March 2019, the park has 17 rollercoasters, the second-most worldwide. However, the extent of the problems affecting the park became apparent very quickly. Two days after the park opened, a train got stuck on top of a roller coaster, and the passengers were forced to leave the merry-go-round on foot.`,
    channelName: "Explomo",
  },

  {
    _id: uuid(),
    title: "Simcha Island Indore | Adventure Park Indore ",
    thumbnail: "https://i.ytimg.com/vi/Tdrn_tIj468/maxresdefault.jpg",
    iframe: `width="100" src="https://www.youtube.com/embed/Tdrn_tIj468" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen="allowFullScreen">`,
    category: "adventure",
    likes: 666,
    liked: null,
    disliked: null,
    notes: [],
    description: "Recently we have visited Simcha Adventure Park Indore. They offer tons of activities like Paint Ball, ATV Ride, Go Karting, Trampoline Park, Zorb Football, Rocket Ejector, Pump Track. They also have some good restaurants where you can enjoy food. If you have a free day and wanna have fun go there and enjoy.",
    channelName: "I Kratika",
  },

  {
    _id: uuid(),
    title: "Post Malone, Swae Lee - Sunflower (Spider-Man: Into the Spider-Verse)",
    thumbnail: "https://i.ytimg.com/vi/ApXoWvfEYVU/maxresdefault.jpg",
    iframe: `width="100" src="https://www.youtube.com/embed/ApXoWvfEYVU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen="allowFullScreen">`,
    category: "music",
    likes: 666,
    liked: null,
    disliked: null,
    notes: [],
    description: `Phil Lord and Christopher Miller, the creative minds behind The Lego Movie and 21 Jump Street, bring their unique talents to a fresh vision of a different Spider-Man Universe, with a groundbreaking visual style that’s the first of its kind. Spider-Man™: Into the Spider-Verse introduces Brooklyn teen Miles Morales, and the limitless possibilities of the Spider-Verse, where more than one can wear the mask. `,
    channelName: "Post Malone",
  },

  {
    _id: uuid(),
    title: "Justin Bieber - Peaches ft. Daniel Caesar, Giveon",
    thumbnail: "https://i.ytimg.com/vi/tQ0yjYUFKAE/maxresdefault.jpg",
    iframe: `width="100" src="https://www.youtube.com/embed/tQ0yjYUFKAE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen="allowFullScreen">`,
    category: "music",
    likes: 666,
    liked: null,
    disliked: null,
    notes: [],
    description: `Justice the album out now:`,
    channelName: "Justin Bieber",
  },

  {
    _id: uuid(),
    title: "Ed Sheeran - Bad Habits [Official Video]",
    thumbnail: "https://i.ytimg.com/vi/orJSJGHjBLI/maxresdefault.jpg",
    iframe: `width="100" src="https://www.youtube.com/embed/orJSJGHjBLI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen="allowFullScreen">`,
    category: "music",
    likes: 666,
    liked: null,
    disliked: null,
    notes: [],
    description: `The official video for Ed Sheeran - Bad Habits`,
    channelName: "Ed Sheeran",
  },

  {
    _id: uuid(),
    title: "Satisfying Relaxing Video With Chilling Music to Fall Asleep",
    thumbnail: "https://i.ytimg.com/vi/Wr6A78FDy_E/maxresdefault.jpg",
    iframe: `width="100" src="https://www.youtube.com/embed/Wr6A78FDy_E" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen="allowFullScreen">`,
    category: "chill",
    likes: 666,
    liked: null,
    disliked: null,
    notes: [],
    description: `We create and license oddly satisfying videos. Welcome to the world of satisfaction.`,
    channelName: "Satisfying World",
  },

  {
    _id: uuid(),
    title: "1 Hour Satisfying Video With Lofi Chill Beats",
    thumbnail: "https://i.ytimg.com/vi/MFCLbiLhfAo/maxresdefault.jpg",
    iframe: `width="100" src="https://www.youtube.com/embed/MFCLbiLhfAo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen="allowFullScreen">`,
    category: "chill",
    likes: 666,
    liked: null,
    disliked: null,
    notes: [],
    description: `Oddly satisfying compilation! Hope you enjoyed. Drop a comment on what you think of the video.
    Dont forget to subscribe for more daily satisfying video's.`,
    channelName: "Amazing Crafts",
  },

  {
    _id: uuid(),
    title: "Satisfying And Relaxation Compilation in Tik Tok #25",
    thumbnail: "https://i.ytimg.com/vi/zkBolfg9gDQ/maxresdefault.jpg",
    iframe: `width="100" src="https://www.youtube.com/embed/zkBolfg9gDQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen="allowFullScreen">`,
    category: "chill",
    likes: 666,
    liked: null,
    disliked: null,
    notes: [],
    description: `#25 Best Oddly Satisfying Video •  Satisfying And Relaxation Compilation in Tik Tok`,
    channelName: "VN Channel",
  },

  {
    _id: uuid(),
    title: "'Secrets of Playboy': The docuseries exposing the dark side Hugh Hefner",
    thumbnail: "https://i.ytimg.com/vi/HFqss1wNcHU/maxresdefault.jpg",
    iframe: `width="100" src="https://www.youtube.com/embed/HFqss1wNcHU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen="allowFullScreen">`,
    category: "docuseries",
    likes: 666,
    liked: null,
    disliked: null,
    notes: [],
    description: `Zeitgeisty and refreshing or dark and manipulative? This 10-part docuseries lifts the lid on the story of Playboy from the women that experienced it.`,
    channelName: "euronews",
  },

  {
    _id: uuid(),
    title: "Hiroshima | English, Part 1 | War docuseries",
    thumbnail: "https://i.ytimg.com/vi/VfanKGiLmfg/maxresdefault.jpg",
    iframe: `width="100" src="https://www.youtube.com/embed/VfanKGiLmfg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen="allowFullScreen">`,
    category: "docuseries",
    likes: 666,
    liked: null,
    disliked: null,
    notes: [],
    description: `** This video may not be suitable for all viewers. Viewer discretion is advised. / Cette vidéo peut ne pas convenir à tous les publics. Nous préférons vous en avertir. **`,
    channelName: "Encore+",
  },

  {
    _id: uuid(),
    title: "Lady Gaga Details Pregnancy After Assault In Devastating Docuseries",
    thumbnail: "https://i.ytimg.com/vi/t7oMFsVDQtU/maxresdefault.jpg",
    iframe: `width="100" src="https://www.youtube.com/embed/t7oMFsVDQtU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen="allowFullScreen">`,
    category: "docuseries",
    likes: 666,
    liked: null,
    disliked: null,
    notes: [],
    description: `In a devastating new interview for Prince Harry’s upcoming documentary series, Lady Gaga opened up about her sexual assault, and the effects that the tragic incident still has on her today. Watch the latest Clevver News Feed.`,
    channelName: "Clevver News",
  },



];
